# ref: https://docs.travis-ci.com/user/languages/python
language: python
python:
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "3.5"
  - "3.6.9"
  #- "3.5-dev" # 3.5 development branch
  #- "nightly" # points to the latest development branch e.g. 3.6-dev
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install connexion[swagger-ui]
# command to run tests
script: nosetests
