# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class OneNotification(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, device_mac: str=None, known: bool=None, name: str=None):  # noqa: E501
        """OneNotification - a model defined in Swagger

        :param device_mac: The device_mac of this OneNotification.  # noqa: E501
        :type device_mac: str
        :param known: The known of this OneNotification.  # noqa: E501
        :type known: bool
        :param name: The name of this OneNotification.  # noqa: E501
        :type name: str
        """
        self.swagger_types = {
            'device_mac': str,
            'known': bool,
            'name': str
        }

        self.attribute_map = {
            'device_mac': 'device_mac',
            'known': 'known',
            'name': 'name'
        }
        self._device_mac = device_mac
        self._known = known
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'OneNotification':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OneNotification of this OneNotification.  # noqa: E501
        :rtype: OneNotification
        """
        return util.deserialize_model(dikt, cls)

    @property
    def device_mac(self) -> str:
        """Gets the device_mac of this OneNotification.


        :return: The device_mac of this OneNotification.
        :rtype: str
        """
        return self._device_mac

    @device_mac.setter
    def device_mac(self, device_mac: str):
        """Sets the device_mac of this OneNotification.


        :param device_mac: The device_mac of this OneNotification.
        :type device_mac: str
        """

        self._device_mac = device_mac

    @property
    def known(self) -> bool:
        """Gets the known of this OneNotification.


        :return: The known of this OneNotification.
        :rtype: bool
        """
        return self._known

    @known.setter
    def known(self, known: bool):
        """Sets the known of this OneNotification.


        :param known: The known of this OneNotification.
        :type known: bool
        """

        self._known = known

    @property
    def name(self) -> str:
        """Gets the name of this OneNotification.


        :return: The name of this OneNotification.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this OneNotification.


        :param name: The name of this OneNotification.
        :type name: str
        """

        self._name = name
